# golangci-lint configuration file
# See https://golangci-lint.run/usage/configuration/

linters:
  enable:
    - bodyclose
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - goconst
    - gocyclo
    - gosec
    - revive
    - stylecheck

  exclusions:
    rules:
      - linters:
          - gosec
        text: G115
run:
  timeout: 5m
  tests: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
